# Generated by Django 5.2.5 on 2025-08-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'ກຳລັງລໍຖ້າອະນຸມັດ'), ('unpaid', 'ຍັງບໍ່ໄດ້ຈ່າຍ'), ('paid', 'ຈ່າຍແລ້ວ'), ('rejected', 'ປະຕິເສດ'), ('cancelled', 'ຍົກເລີກ')], default='pending', max_length=20, verbose_name='ສະຖານະ'),
        ),
    ]
