# Generated by Django 5.2.5 on 2025-09-03 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersIdGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_running_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTenantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='ຊື່ Tenant')),
                ('tenant_domain', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tenant Domain')),
            ],
            options={
                'verbose_name': 'ຊື່ Tenant',
                'verbose_name_plural': 'ຊື່ Tenant',
            },
        ),
        migrations.CreateModel(
            name='CustomersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=30)),
                ('contact_person_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('company_address', models.CharField(max_length=255)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_customers.customertenantmodel', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນກ່ຽວກັບລູກຄ້າ',
                'verbose_name_plural': 'ຂໍ້ມູນກ່ຽວກັບລູກຄ້າ',
                'ordering': ('-create_at',),
            },
        ),
    ]
