# Generated by Django 5.2.5 on 2025-09-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='tenant_domain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customersmodel',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
