# Generated by Django 5.2.5 on 2025-09-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0002_customersmodel_tenant_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTenantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='ຊື່ Tenant')),
                ('tenant_domain', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tenant Domain')),
            ],
            options={
                'verbose_name': 'ຊື່ Tenant',
                'verbose_name_plural': 'ຊື່ Tenant',
            },
        ),
        migrations.RemoveField(
            model_name='customersmodel',
            name='tenant_domain',
        ),
        migrations.RemoveField(
            model_name='customersmodel',
            name='tenant_name',
        ),
        migrations.AddField(
            model_name='customersmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_customers.customertenantmodel', verbose_name='Tenant'),
        ),
    ]
