# Generated by Django 5.2.5 on 2025-09-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinformationmodel',
            name='created_at_log',
        ),
        migrations.RemoveField(
            model_name='quotationinformationmodel',
            name='updated_at_log',
        ),
    ]
