# Generated by Django 5.2.5 on 2025-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsModel',
            fields=[
                ('contract_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_contract', models.DateField(verbose_name='ວັນທີອອກສັນຍາ')),
                ('end_contract', models.DateField(verbose_name='ວັນທີຫມົດສັນຍາ')),
                ('status', models.CharField(choices=[('Draft', 'ຮ່າງ'), ('Active', 'ກຳລັງໃຊ້ງານ'), ('Expired', 'ຫມົດອາຍຸການນຳໃຊ້'), ('Banned', 'ລະງັບ')], default='Draft', max_length=30, verbose_name='ສະຖານະຂອງສັນຍາ')),
            ],
            options={
                'verbose_name': 'ຈັດການສັນຍາ',
                'verbose_name_plural': 'ຈັດການສັນຍາ',
            },
        ),
        migrations.CreateModel(
            name='GenerateContractNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_number', models.BigIntegerField(default=0)),
            ],
        ),
    ]
