# Generated by Django 5.2.5 on 2025-09-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_employee', '0002_initial'),
        ('app_invoices', '0001_initial'),
        ('app_po', '0001_initial'),
        ('app_quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateContractNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_number', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContractsModel',
            fields=[
                ('contract_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_contract', models.DateField(verbose_name='ວັນທີອອກສັນຍາ')),
                ('end_contract', models.DateField(verbose_name='ວັນທີຫມົດສັນຍາ')),
                ('status', models.CharField(choices=[('Draft', 'ຮ່າງ'), ('Active', 'ກຳລັງໃຊ້ງານ'), ('Expired', 'ຫມົດອາຍຸການນຳໃຊ້'), ('Banned', 'ລະງັບ')], default='Draft', max_length=30, verbose_name='ສະຖານະຂອງສັນຍາ')),
                ('upload_contract', models.FileField(blank=True, null=True, upload_to='contract_docs/', verbose_name='ເອກະສານສັນຍາ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee', to='app_employee.employeesmodel', verbose_name='ພະນັກງານຮັບຜິດຊອບ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_customer', to='app_customers.customersmodel', verbose_name='ລູກຄ້າ')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_invoice', to='app_invoices.invoicemodel', verbose_name='ໃບເກັບເງິນທີ່ກ່ຽວຂ້ອງ')),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_po', to='app_po.purchaseordermodel', verbose_name='ໃບສັ່ງຊື້ທີ່ກ່ຽວຂ້ອງ')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_quotation', to='app_quotations.quotationinformationmodel', verbose_name='ໃບສະເຫນີລາຄາທີ່ກ່ຽວຂ້ອງ')),
            ],
            options={
                'verbose_name': 'ຈັດການສັນຍາ',
                'verbose_name_plural': 'ຈັດການສັນຍາ',
            },
        ),
    ]
