# Generated by Django 5.2.5 on 2025-09-02 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0003_customertenantmodel_and_more'),
        ('app_employee', '0002_initial'),
        ('app_invoices', '0002_alter_invoicemodel_status'),
        ('app_po', '0016_approvedpomodel_signature_approvedpomodel_stamp_and_more'),
        ('app_quotations', '0002_remove_quotationinformationmodel_created_at_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsModel',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_contract', models.DateField(verbose_name='ວັນທີອອກສັນຍາ')),
                ('end_contract', models.DateField(verbose_name='ວັນທີຫມົດສັນຍາ')),
                ('status', models.CharField(choices=[('Draft', 'ຮ່າງ'), ('Active', 'ກຳລັງໃຊ້ງານ'), ('Expired', 'ຫມົດອາຍຸການນຳໃຊ້'), ('Banned', 'ລະງັບ')], default='Draft', max_length=30, verbose_name='ສະຖານະຂອງສັນຍາ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_customer', to='app_customers.customersmodel', verbose_name='ລູກຄ້າ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee', to='app_employee.employeesmodel', verbose_name='ພະນັກງານຮັບຜິດຊອບ')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_invoice', to='app_invoices.invoicemodel', verbose_name='ໃບເກັບເງິນທີ່ກ່ຽວຂ້ອງ')),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_po', to='app_po.purchaseordermodel', verbose_name='ໃບສັ່ງຊື້ທີ່ກ່ຽວຂ້ອງ')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_quotation', to='app_quotations.quotationinformationmodel', verbose_name='ໃບສະເຫນີລາຄາທີ່ກ່ຽວຂ້ອງ')),
            ],
            options={
                'verbose_name': 'ຈັດການສັນຍາ',
                'verbose_name_plural': 'ຈັດການສັນຍາ',
            },
        ),
    ]
