# Generated by Django 5.2.5 on 2025-09-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contracts', '0001_initial'),
        ('app_customers', '0001_initial'),
        ('app_employee', '0001_initial'),
        ('app_invoices', '0001_initial'),
        ('app_po', '0001_initial'),
        ('app_quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee', to='app_employee.employeesmodel', verbose_name='ພະນັກງານຮັບຜິດຊອບ'),
        ),
        migrations.AddField(
            model_name='contractsmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_customer', to='app_customers.customersmodel', verbose_name='ລູກຄ້າ'),
        ),
        migrations.AddField(
            model_name='contractsmodel',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_invoice', to='app_invoices.invoicemodel', verbose_name='ໃບເກັບເງິນທີ່ກ່ຽວຂ້ອງ'),
        ),
        migrations.AddField(
            model_name='contractsmodel',
            name='po',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_po', to='app_po.purchaseordermodel', verbose_name='ໃບສັ່ງຊື້ທີ່ກ່ຽວຂ້ອງ'),
        ),
        migrations.AddField(
            model_name='contractsmodel',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_quotation', to='app_quotations.quotationinformationmodel', verbose_name='ໃບສະເຫນີລາຄາທີ່ກ່ຽວຂ້ອງ'),
        ),
    ]
