# Generated by Django 5.2.5 on 2025-09-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractsmodel',
            old_name='employee',
            new_name='created_by',
        ),
    ]
