# Generated by Django 5.2.5 on 2025-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0002_rename_employee_contractsmodel_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateContractNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_number', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='contractsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='contract_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
