# Generated by Django 5.2.6 on 2025-09-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsmodel',
            name='upload_contract',
            field=models.FileField(blank=True, null=True, upload_to='contract_docs/', verbose_name='ເອກະສານສັນຍາ'),
        ),
    ]
