# Generated by Django 5.2.5 on 2025-09-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0002_add_upload_contract'),
        ('app_contracts', '0003_create_generatecontractnumber'),
    ]

    operations = [
    ]
