# Generated by Django 5.2.5 on 2025-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0003_generatecontractnumber_contractsmodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='contract_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
