# Generated by Django 5.2.6 on 2025-09-05 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0004_merge_20250904_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsmodel',
            name='contract_number',
            field=models.CharField(default='TEMP-CONTRACT', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='contract_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
