# Generated by Django 5.2.6 on 2025-09-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contracts', '0005_contractsmodel_contract_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsmodel',
            name='contract_number',
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='contract_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
