# Generated by Django 5.2.5 on 2025-08-28 09:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_employee', '0002_initial'),
        ('app_invoices', '0002_alter_invoicemodel_status'),
        ('app_quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ຊື່')),
                ('last_name', models.CharField(max_length=30, verbose_name='ນາມສະກຸນ')),
                ('position', models.CharField(choices=[('ceo', 'ceo'), ('cto', 'cto'), ('manager', 'Manager')], max_length=20, verbose_name='ຕຳແຫນ່ງ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ຫມາຍເຫດ')),
            ],
            options={
                'verbose_name': 'ຜູ້ອະນຸມັດໃບສັ່ງຊື້',
                'verbose_name_plural': 'ຜູ້ອະນຸມັດໃບສັ່ງຊື້',
            },
        ),
        migrations.CreateModel(
            name='PoIdGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number_generator', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PO Number Generator',
                'verbose_name_plural': 'PO Number Generators',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(max_length=20, unique=True, verbose_name='ລະຫັດໃບສັ່ງຊື້')),
                ('start_date', models.DateField(verbose_name='ວັນທີ່ເລີ່ມຕົ້ນ')),
                ('end_date', models.DateField(verbose_name='ວັນທີ່ສິ້ນສຸດ')),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າອະນຸມັດ'), ('completed', 'ສຳເລັດ'), ('rejected', 'ປະຕິເສດ'), ('cancelled', 'ຍົກເລີກ'), ('banned', 'ຖືກລະງັບ')], default='pending', max_length=20, verbose_name='ສະຖານະ')),
                ('total_all_products', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='ລາຄາລວມທັງໝົດ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to='app_po.approvedpomodel', verbose_name='ອະນຸມັດໂດຍ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app_employee.employeesmodel', verbose_name='ພະນັກງານຮັບຜິດຊອບ')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='app_invoices.invoicemodel', verbose_name='ໃບເກັບເງິນ')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='app_quotations.quotationinformationmodel', verbose_name='ໃບສະເຫນີລາຄາ')),
            ],
            options={
                'verbose_name': 'ໃບສັ່ງຊື້',
                'verbose_name_plural': 'ໃບສັ່ງຊື້',
                'ordering': ['-po_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='ຊື່ສິນຄ້າ')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ລາຄາ')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='ຈຳນວນ')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='ລະດັບເວລາ (ເດືອນ)')),
                ('total_one_product', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='ລາຄາລວມ')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_po.purchaseordermodel', verbose_name='ໃບສັ່ງຊື້')),
            ],
            options={
                'verbose_name': 'ລາຍການໃນໃບສັ່ງຊື້',
                'verbose_name_plural': 'ລາຍການໃນໃບສັ່ງຊື້',
            },
        ),
    ]
