# Generated by Django 5.2.5 on 2025-08-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedpomodel',
            name='position',
            field=models.CharField(max_length=50, verbose_name='ຕຳແຫນ່ງ'),
        ),
    ]
