# Generated by Django 5.2.5 on 2025-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0002_alter_approvedpomodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitemsmodel',
            name='period',
            field=models.PositiveIntegerField(default=12, verbose_name='ລະດັບເວລາ (ເດືອນ)'),
        ),
    ]
