# Generated by Django 5.2.5 on 2025-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0003_alter_purchaseorderitemsmodel_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='approved_po',
            field=models.FileField(blank=True, null=True, upload_to='approved_po/', verbose_name='ອະນຸມັດໃບສັ່ງຊື້'),
        ),
    ]
