# Generated by Django 5.2.5 on 2025-09-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_po', '0004_purchaseordermodel_approved_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app_customers.customersmodel', verbose_name='ລູກຄ້າ'),
        ),
    ]
