# Generated by Django 5.2.5 on 2025-09-02 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_po', '0005_purchaseordermodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app_customers.customersmodel', verbose_name='ລູກຄ້າ'),
        ),
    ]
