# Generated by Django 5.2.5 on 2025-09-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0006_alter_purchaseordermodel_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='ຊືຜູ້ສະຫນອງ')),
                ('supplier_address', models.CharField(max_length=255, verbose_name='ທີ່ຢູ່ຂອງຜູ້ສະຫນອງ')),
                ('supplier_contact', models.CharField(max_length=20, verbose_name='ເບີໂທຂອງຜູ້ສະຫນອງ')),
                ('supplier_email', models.EmailField(max_length=50, verbose_name='ອີເມວຂອງຜູ້ສະຫນອງ')),
            ],
            options={
                'verbose_name': 'ຜູ້ສະຫນອງ',
                'verbose_name_plural': 'ຜູ້ສະຫນອງ',
            },
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_po', to='app_po.suppliersmodel', verbose_name='ເລືອກຜູ້ສະຫນອງ'),
        ),
    ]
