# Generated by Django 5.2.5 on 2025-09-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0007_suppliersmodel_purchaseordermodel_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliersmodel',
            old_name='supplier_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='suppliersmodel',
            old_name='supplier_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='suppliersmodel',
            old_name='supplier_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='suppliersmodel',
            old_name='supplier_name',
            new_name='name',
        ),
    ]
