# Generated by Django 5.2.5 on 2025-09-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0008_rename_supplier_address_suppliersmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='billing_plan',
            field=models.CharField(choices=[('monthly/monthly', 'ຊຳລະແບບລາຍເດືອນ'), ('anual_monthly/anual_monthly', 'ສັນຍາລາຍປີ, ຊຳລະເປັນເດືອນ'), ('anual', 'ຊຳລະທັງຫມົດປີ')], default='anual', max_length=30, verbose_name='ຮູບແບບການຊຳລະ'),
        ),
    ]
