# Generated by Django 5.2.5 on 2025-09-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0003_customertenantmodel_and_more'),
        ('app_po', '0009_purchaseordermodel_billing_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_po', to='app_customers.customertenantmodel', verbose_name='Tenant'),
        ),
    ]
