# Generated by Django 5.2.5 on 2025-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0010_purchaseordermodel_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersmodel',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ແຟັກ'),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ອີເມວຂອງຜູ້ສະຫນອງ'),
        ),
    ]
