# Generated by Django 5.2.5 on 2025-09-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0011_suppliersmodel_fax_alter_suppliersmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliersmodel',
            name='address',
        ),
        migrations.AddField(
            model_name='suppliersmodel',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ທີ່ຢູ່ຂອງຜູ້ສະຫນອງ 1'),
        ),
        migrations.AddField(
            model_name='suppliersmodel',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ທີ່ຢູ່ຂອງຜູ້ສະຫນອງ 2'),
        ),
    ]
