# Generated by Django 5.2.5 on 2025-09-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0012_remove_suppliersmodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliersmodel',
            name='contact',
        ),
        migrations.AddField(
            model_name='suppliersmodel',
            name='contact_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ເບີໂທຂອງຜູ້ສະຫນອງ'),
        ),
        migrations.AddField(
            model_name='suppliersmodel',
            name='contact_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ເບີໂທຂອງຜູ້ສະຫນອງ 2'),
        ),
    ]
