# Generated by Django 5.2.5 on 2025-09-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0013_remove_suppliersmodel_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='start_date',
            field=models.DateField(verbose_name='ວັນທີ່ອອກ'),
        ),
    ]
