# Generated by Django 5.2.5 on 2025-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0014_remove_purchaseordermodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='signatured_date',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນທີຮັບຮອງແລ້ວ'),
        ),
    ]
