# Generated by Django 5.2.5 on 2025-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_po', '0015_purchaseordermodel_signatured_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedpomodel',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='approver_signatures', verbose_name='ລາຍເຊັນ'),
        ),
        migrations.AddField(
            model_name='approvedpomodel',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='approver_stamps', verbose_name='ກາຈ້ຳຂອງບໍລິສັດ'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='signatured_date',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນທີຮັບຮອງອະນຸມັດໃບສັ່ງຊື້'),
        ),
    ]
